export class EventService {
    constructor(protected db) {
        db.serialize(function () {
            db.run(
                `CREATE TABLE IF NOT EXISTS users 
                (
                    user_id       integer generated BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email         text                        NOT NULL UNIQUE,
                    role          user_role                   NOT NULL DEFAULT 'member',
                    name          text                        NOT NULL,
                    created_at    text NOT NULL default (now() at time zone 'utc'),
                    deleted_at    text NULL     DEFAULT NULL,
                    api_key       text UNIQUE                          default generate_api_key(20) not null,
                    jwt_iat       text NULL     DEFAULT NULL,
                    data          jsonb                       NOT NULL DEFAULT '{}'::jsonb,
                    weekly_report boolean                     NOT NULL DEFAULT TRUE
                );`,
                err => {
                    if (err !== null) {
                        throw err;
                    }
                    console.log('create table event');
                }
            );
        });
    }
}

export class EventControl {
    constructor() {}

    toJSON() {
        return [
            {
                sessionId: 6452555841131295,
                messageId: 3,
                timestamp: 1648458188705,
                host: 'www.jisilu.cn',
                path: '/web/data/cb/list',
                referrer: 'https://www.jisilu.cn/',
                domContentLoadedTime: 327,
                firstPaintTime: 198,
                firstContentfulPaintTime: 471,
                loadTime: 328,
                speedIndex: 513,
                visuallyComplete: 20007,
                timeToInteractive: null,
                domBuildingTime: 281,
                basePath: '/web/data/cb/list',
                baseReferrer: 'https://www.jisilu.cn/',
                responseTime: 1,
                responseEnd: 46,
                ttfb: null,
                value: '/web/data/cb/list',
                url: '/web/data/cb/list',
                type: 'LOCATION',
            },
            {
                sessionId: 6452555841131295,
                messageId: 4294967299,
                timestamp: 1648458216725,
                host: 'www.jisilu.cn',
                path: '/web/data/cb/list',
                referrer: 'https://www.jisilu.cn/login/',
                domContentLoadedTime: 351,
                firstPaintTime: 134,
                firstContentfulPaintTime: 593,
                loadTime: 358,
                speedIndex: 593,
                visuallyComplete: 3718,
                timeToInteractive: 4879,
                domBuildingTime: 308,
                basePath: '/web/data/cb/list',
                baseReferrer: 'https://www.jisilu.cn/login/',
                responseTime: 1,
                responseEnd: 43,
                ttfb: null,
                value: '/web/data/cb/list',
                url: '/web/data/cb/list',
                type: 'LOCATION',
            },
        ];
    }
}
