export class UserService {
    constructor(protected db) {
        db.serialize(function () {
            // db.run('DROP TABLE IF EXISTS "sessions";');
            db.run(
                `CREATE TABLE IF NOT EXISTS users 
                (
                    user_id       integer generated BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email         text                        NOT NULL UNIQUE,
                    role          user_role                   NOT NULL DEFAULT 'member',
                    name          text                        NOT NULL,
                    created_at    text NOT NULL default (now() at time zone 'utc'),
                    deleted_at    text NULL     DEFAULT NULL,
                    api_key       text UNIQUE                          default generate_api_key(20) not null,
                    jwt_iat       text NULL     DEFAULT NULL,
                    data          jsonb                       NOT NULL DEFAULT '{}'::jsonb,
                    weekly_report boolean                     NOT NULL DEFAULT TRUE
                );`,
                err => {
                    if (err !== null) {
                        throw err;
                    }
                    console.log('create table sessions');
                }
            );
        });
    }
}
